GET http://localhost:3000/author
Content-type: application/json

{
    "firstName": "Test",
    "lastName": "Testovich",
    "email": "test@test.gmail.com",
    "message": "This is first test message"
}